name: "doc-to-podcast"
version: "0.2.0"
description: "Convert documents to engaging podcast content with AI-powered voice synthesis"

processing:
  chunk_size: 32768
  max_chars: 1000000
  overlap: 512
  
models:
  text_generation:
    provider: "anthropic"
    default: "claude-3-haiku-20240307" # "claude-3-5-sonnet-20241022"
    fallback: "claude-3-haiku-20240307"
    temperature: 0.7
    top_p: 0.9
    max_new_tokens: 4096
  
  voice_synthesis:
    primary:
      name: "F5-TTS"
      type: "f5tts"
      model_path: "hf://SWivid/F5-TTS/F5TTS_Base/model_1200000.safetensors"
      sampling_rate: 24000
      ode_method: "euler"
      nfe_step: 32
      cfg_strength: 2
      target_rms: 0.1
    secondary:
      name: "E2-TTS"
      type: "f5tts"
      model_path: "hf://SWivid/E2-TTS/E2TTS_Base/model_1200000.safetensors"
      sampling_rate: 24000
      ode_method: "euler"
      nfe_step: 32
      cfg_strength: 2
      target_rms: 0.1

output:
  audio:
    format: "mp3"
    bitrate: "192k"
    parameters:
      - "-q:a"
      - "0"
  
  transcript:
    format: "txt"
    include_timestamps: true
    include_speaker_labels: true
  
  script_dir: "outputs/scripts"
  audio_dir: "outputs/audio"
  segments_dir: "outputs/segments"

workflow:
  steps:
    - name: "document_processing"
      enabled: true
      timeout: 300
    - name: "content_generation"
      enabled: true
      timeout: 600
    - name: "voice_synthesis" 
      enabled: true
      timeout: 900

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  handlers:
    - type: "console"
    - type: "file"
      filename: "doc2podcast.log"
