tasks:
  document_analysis:
    description: >
      Analyze the following document content and extract key insights:
      {content}
      
      Focus on:
      1. Main arguments and findings
      2. Key methodology details
      3. Important implications
      4. Notable quotes or statistics
      
      Provide a structured analysis suitable for podcast adaptation.
    expected_output: "Structured analysis with key points and insights"
    agent: "document_processor"
    parameters:
      chunk_size: 1000
      max_chars: 100000
      overlap: 200
    validation:
      required_fields:
        - processed_text
        - metadata
      output_format: "json"

  content_strategy:
    description: >
      Create a podcast content strategy using:
      Content: {content}
      Format: {preset}
      Target Audience: {target_audience}
      Expertise Level: {expertise_level}
      Additional Guidance: {guidance}
      
      Requirements:
      1. Plan episode structure following the format template
      2. Identify key discussion points and transitions
      3. Adapt content complexity for target audience
      4. Consider expertise level in technical depth
      5. Incorporate format-specific elements
      
      Return a detailed content strategy with segment planning.
    
    expected_output: "JSON with content strategy and segment planning"
    agent: "content_strategist"
    parameters:
      min_segments: 3
      max_segments: 10
      include_transitions: true
    validation:
      required_fields:
        - episode_structure
        - key_points
        - transitions
      output_format: "json"

  script_writing:
    description: >
      Using this content strategy, create a podcast script:
      {strategy}
      
      Consider:
      Target Audience: {target_audience}
      Expertise Level: {expertise_level}
      
      Requirements:
      1. Create natural dialogue between speakers
      2. Follow the episode structure
      3. Include clear speaker indicators
      4. Add appropriate transitions
      5. Match content to audience level
      
      Format as a structured conversation script.
    
    expected_output: "JSON with dialogue script"
    agent: "script_writer"
    parameters:
      temperature: 0.7
      max_tokens: 8126
      style: "conversational"
    validation:
      required_fields:
        - segments
        - speakers
        - metadata
      output_format: "json"

  voice_optimization:
    description: >
      Optimize this script for voice synthesis:
      {script}
      
      Using these voice profiles:
      {voices}
      
      Requirements:
      1. Adapt text for natural speech patterns
      2. Add pronunciation guidance
      3. Optimize pacing and emphasis
      4. Consider voice characteristics
      5. Balance segment lengths
      
      Return voice-optimized script.
    
    expected_output: "JSON with optimized script"
    agent: "voice_optimizer"
    parameters:
      target_duration: 1800
      include_markers: true
    validation:
      required_fields:
        - segments
        - voice_guidance
        - timing
      output_format: "json"

  quality_control:
    description: >
      Review and optimize this script:
      {script}
      
      For audience:
      Target: {target_audience}
      Level: {expertise_level}
      
      Check for:
      1. Content accuracy and clarity
      2. Natural conversation flow
      3. Appropriate pacing
      4. Technical accuracy
      5. Audience engagement
      
      Provide improvements and final script.
    
    expected_output: "JSON with final script and quality metrics"
    agent: "quality_checker"
    parameters:
      min_quality_score: 0.8
      check_points:
        - content_accuracy
        - conversation_flow
        - audience_fit
    validation:
      required_fields:
        - final_script
        - quality_metrics
        - improvements
      output_format: "json"

  voice_synthesis:
    description: "Generate audio from script"
    expected_output: "High-quality podcast audio"
    agent: "voice_synthesizer"
    parameters:
      sample_rate: 24000
      audio_quality: "high"
      formats:
        - mp3
        - wav
    validation:
      required_fields:
        - audio_file
        - metadata
      output_format: "json"
